### ISSUE TITLE
Remove v8x16.shuffle and update tests

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasmparser#113]
cont #110 

Per https://github.com/WebAssembly/simd/commit/7f4d54d4c9a525f6e04c7edcecdc1969f27e5d09 , the `v8x16.shuffle` instruction is replaced. Let's remove that from wasmparser and update the test

**Comment by alexcrichton** [comment]
I believe this has since happened in the meantime, so closing.
