### ISSUE TITLE
Getting the values of exported globals when parsing

### ISSUE THREAD

**Issue by hrydgard** [bytecodealliance/wasmparser#114]
I'd like to retrieve the value of an exported global int64 while parsing, and I can't seem to figure out how to do that with the current API.

I'm doing sort of like:
```
match *parser.read() {
    ParserState::ExportSectionEntry {
        field, ref kind, index,
    } => {
       // what to put here?
    }
}
```

I could maybe stash away the index of the one where field matches the name of the exported global I'm looking for, and then run the parser again looking for that index - but when the globals come through in ParserState::BeginGlobalSectionEntry , all you get is the type, and not the index of the global. So that also doesn't get us anywhere.

Any ideas?

**Comment by yurydelendik** [comment]
Globals values in WebAssembly defined as expression (and not values) -- see https://webassembly.github.io/spec/core/syntax/instructions.html#syntax-expr. You need to read these using the logic similar to what you will use for reading function body -- at `BeginInitExpressionBody` state. Though globals init expressions are a [constant](https://webassembly.github.io/spec/core/valid/instructions.html#constant-expressions) expression, so specialized reader can be created.

Please notice that your question is about older API. You may find using section readers (introduced by https://github.com/yurydelendik/wasmparser.rs/pull/68) a better fit for your needs.

Closing as answered.
