### ISSUE TITLE
`simd_load_extend.wast` fails due to `align` modifier

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmparser#159]
If we [re-enable the `simd_load_extend.wast` spec test](https://github.com/bytecodealliance/wasmparser/blob/de273bad6dafb6350e9912df50f2a098b5466348/src/tests.rs#L476), we find that it fails:

```
thread 'tests::wast_tests::run_proposals_tests' panicked at 'simd_load_extend.wast:3: invalid module: Unexpected memarg alignment', src/tests.rs:406:25
```

In discussing with @yurydelendik we considered that possibly the [binary reader alignment comparison](https://github.com/bytecodealliance/wasmparser/blob/88681f9a85a6404d14a2ec1167ad7960b5f32e2c/src/binary_reader.rs#L711) is incorrect (should it be a `>`?) or possibly `wasmparser` is receiving an incorrect alignment from `wast` (cc @alexcrichton).

[potential issue]: https://github.com/bytecodealliance/wasmparser/blob/88681f9a85a6404d14a2ec1167ad7960b5f32e2c/src/binary_reader.rs#L711

**Comment by alexcrichton** [comment]
I think that this may have been fixed with the most recent `wat` PR, want to update that and see if this still fails?
