### ISSUE TITLE
Avoid dynamic allocation for BrTable decoding

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmparser#16]
BrTable is currently the only Operator member that requires dynamic allocation. It's desirable to avoid dynamic allocation during decoding in general, and eliminating this instance of it would eliminate the need for `drop` calls in the compiled code for Operator.

One way to do this would be to have BrTable hold an iterator, which then decodes the table contents on demand, instead of copying them into a Vec. A possible variant of this would be to make it return a slice of the input buffer, which could then be decoded on demand.

**Comment by yurydelendik** [comment]
Fixed by 813ba12

**Comment by yurydelendik** [comment]
Forgot iterator

**Comment by yurydelendik** [comment]
Fixed by 76b5546b5556bb45572c620ce936c9e3439b95b0
