### ISSUE TITLE
`linking.wast` fails when anyfunc is not used in active tables

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmparser#161]
When running the reference type spec test `linking.wast`, it fails due to the following assertion:

```
thread 'tests::wast_tests::run_proposals_tests' panicked at 'assertion failed: self.resources.tables[table_index as usize].element_type == Type::AnyFunc', src/validator.rs:532:21
```

**Comment by yurydelendik** [comment]
commited https://github.com/bytecodealliance/wasmparser/commit/9a72ceff6f9e006acbfdc8efabd6087ef42fc235 to reduce affect on testing

new https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md in effect: element_type is allowed to be externval and elemexpr
