### ISSUE TITLE
Multiple SIMD spec tests fail due to invalid assert_return_* tokens

### ISSUE THREAD

**Issue by abrown** [bytecodealliance/wasmparser#163]
Several SIMD spec tests (`simd_f32x4_arith.wast`, `simd_f64x2_arith.wast`, `simd_f32x4.wast`, `simd_f64x2.wast`) fail due to an invalid token:

```
thread 'tests::wast_tests::run_proposals_tests' panicked at 'called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { text: Some(Text { line: 729, col: 1, snippet: "(assert_return_canonical_nan_f64x2 (invoke \"f64x2.add\" (v128.const f64x2 inf inf)" }), file: Some("simd_f64x2_arith.wast"), span: Span { offset: 61868 }, kind: Custom("unexpected token, expected one of: `module`, `assert_malformed`, `assert_invalid`, `register`, `invoke`, `assert_trap`, `assert_return`, `assert_return_canonical_nan`, `assert_return_arithmetic_nan`, `assert_return_func`, `assert_exhaustion`, `assert_unlinkable`") } }', src/libcore/result.rs:1165:5
```

This issue should be resolved by:
 - once https://github.com/WebAssembly/simd/pull/156 is merged
 - once wasmparser understands the new `assert_return` syntax
 - once wast understands the new `assert_return` syntax (cc @alexcrichton)

**Comment by alexcrichton** [comment]
I think this may just require a `wast` update since you've implementing parsing for this directive?
