### ISSUE TITLE
Split instruction decoding into a separate interface

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmparser#17]
Right now, `parser.read()` handles everything. It's a simple interface, and great for [writing a dump command](https://github.com/yurydelendik/wasmparser.rs/pull/15), however in more advanced contexts, such as when doing parallel compilation of function bodies, it's useful to be able to decode function bodies independently. And, when decoding a function body, it's inconvenient and possibly inefficient for consumers to have to match on the full `ParserState` for each instruction when they know there are only going to be `Operator`s until the end of the function.

One way to start addressing these needs would be to add a `read_instruction` function, which returns an `Operator`. After `parser.read()` returns a `BeginFunctionBody`, consumers could just call `parser.read_instruction()` until they reach the end of the function body.

**Comment by yurydelendik** [comment]
There is read_with_input() function, see https://docs.rs/wasmparser/0.4.7/wasmparser/struct.Parser.html#method.read_with_input

**Comment by sunfishcode** [comment]
For the parallel compilation use case, we know where the function body starts. It would likely be inefficient to have to rediscover where a given function starts by skipping sections and function bodies until arriving at the desired one.

Also, while it's possible to create a `parser` in an appropriate state to start decoding at a single function body, I also think it'd be more convenient to have an interface specialized for function bodies, and possibly more efficient too. Instead of doing `match` on a `ParserState`, getting the `Operator`, and doing a `match` on that, a dedicated interface that returns an `Operator` would allow consumers to just do a single `match` for each instruction.

**Comment by yurydelendik** [comment]
Fixed by https://github.com/yurydelendik/wasmparser.rs/commit/262e82944f38519cb97c63f8a443805500bd49ae -- it's possible to get bytecode range for a section and a function body, as well as instantiate a `BinaryReader` that will read operators or other primitive types.
