### ISSUE TITLE
Figure out how to add fuzz testing

### ISSUE THREAD

**Issue by yurydelendik** [bytecodealliance/wasmparser#22]
More generic case of #21

We will need repeatable way to run fuzzing. Help is needed to add this to the project (e.g. add run-fuzz.sh utility).

/cc @frewsxcv

**Comment by frewsxcv** [comment]
I can open a PR for this later today

**Comment by sunfishcode** [comment]
With #23 merged, can this issue be closed?

**Comment by yurydelendik** [comment]
> With #23 merged, can this issue be closed?

Yes, thanks.
