### ISSUE TITLE
read_operator API

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmparser#25]
I'm looking into whether wasm2cretonne can use the `read_operator` interface (discussed in https://github.com/yurydelendik/wasmparser.rs/issues/17). The code is here:

https://github.com/denismerigoux/wasm2cretonne/blob/master/lib/wasm2cretonne/src/code_translator.rs#L236

While it would be possible to construct a `BinaryReader` at that point, using the range provided from the BeginFunctionBody, however that would require the code to pass around the underlying data buffer, separately from the parser. Since the parser already has the buffer, and knows where it is in the buffer, would it be feasible for the parser to have a `read_operator` function itself? Or, could the parser have a function that returns its BinaryReader? Or is there a better way to do this?

**Comment by yurydelendik** [comment]
I added create_binary_reader(), which can create a BinaryReader as BeginFunctionBody state. See 808451451ef67965f2c4b43ea83dbb0159782849

**Comment by yurydelendik** [comment]
and 2cec415c1637e777d8aa6281d9dc895d74141704 for validation reading
