### ISSUE TITLE
Use enums with named values.

### ISSUE THREAD

**Issue by mbebenita** [bytecodealliance/wasmparser#3]
Can we use enums with names values, so instead of:

```rust
pub enum ParserState<'a> {
  BeginWasm(u32, u32),
}
```
something like
```rust
pub enum ParserState<'a> {
  BeginWasm {magic_number: u32, version: u32},
}
```

I feel like this would help with documentation. I tried switching the code to do this and I ran into a bunch of errors. I don't know Rust very well so I don't know if there are any drawbacks to this.

**Comment by yurydelendik** [comment]
Fixed by https://github.com/yurydelendik/wasmparser.rs/commit/c05bb9d0017e77914c06174c6513833461cdaec9
