### ISSUE TITLE
Problems with LEB128 deocoding

### ISSUE THREAD

**Issue by pepyakin** [bytecodealliance/wasmparser#48]
This [module](https://github.com/WebAssembly/testsuite/blob/8958a44bf8b3dbf9e48dd1c44ee566e8bf682abe/binary.wast#L190) is malformed. However, wasmparser successfully parses it.

See:

- https://github.com/WebAssembly/spec/issues/746
- https://github.com/WebAssembly/wabt/issues/799

**Comment by yurydelendik** [comment]
Fixed by 73ef07095e61b84acab56629311bdaa4ec446374 , thanks.
