### ISSUE TITLE
Move the testsuite to a separate crate

### ISSUE THREAD

**Issue by sunfishcode** [bytecodealliance/wasmparser#55]
Looking ahead to using this in Firefox, the Firefox build system vendors all of its Rust dependencies. For the current wasmparser.rs tree, this would entail copying 7 MiB of test binaries into the tree. Would it be feasible to move the test binaries to a separate crate?

One option would be to move to a [workspace-like setup](https://doc.rust-lang.org/book/second-edition/ch14-03-cargo-workspaces.html) with multiple crates in the same repository, so developers could still easily run the tests, but they wouldn't be included for people using wasmparser.rs as a dependency.

**Comment by pepyakin** [comment]
Is it worth it to use the official testsuite with wabt-rs?

**Comment by yurydelendik** [comment]
Fixed in b515efefd889edc3a36011c922dc249ca617134f by not publishing tests binary files to the crates.io
